### ISSUE TITLE
Naming issues

### ISSUE THREAD

**Issue by tocuto** [Seniru/Timers4TFM#7]
https://github.com/Seniru/Timers4TFM/blob/d3e7ebc020dfc7070f48ac5f5751df7c099fabd0/src/timer.lua#L186

You store the callback as instance.call, but you store the call function as instance.call too. If you don't define any callback, instance:call() would infinitely loop.

You'd rather store the callback as instance.callback

**Comment by Lautenschlager-id** [comment]
Did it in https://github.com/Seniru/Timers4TFM/pull/8

**Comment by Seniru** [comment]
Ahh! What a mistake.

**Comment by Seniru** [comment]
@all-contributors please add @Tocutoeltuco for bug
